name: Baron
description: A new Flutter project.

version: 1.0.3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  showcaseview: ^0.1.2
  provider: ^3.1.0
  font_awesome_flutter: ^8.5.0
  cloud_firestore: ^0.12.9+2
  firebase_dynamic_links: ^0.5.0+1
  firebase_auth: ^0.14.0+5
  in_app_purchase: ^0.2.1
  firebase_admob: ^0.9.0
  share: ^0.6.2+1
  cached_network_image: ^1.1.1
  google_sign_in: ^4.0.7
  firebase_messaging: ^5.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
