name: Baron
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  showcaseview: ^0.1.2
  provider: ^3.1.0
  flare_flutter: ^1.5.7
  font_awesome_flutter: ^8.5.0
  audioplayer: ^0.5.2
  flutter_offline: ^0.2.4+1
  flutter_local_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: true
  ios: true
  image_path: assets/logos/icon.png


flutter:
  uses-material-design: true

  assets:
   - assets/logos/Bronze_1.png
   - assets/logos/Bronze_2.png
   - assets/logos/Crown.png
   - assets/logos/Diamond.png
   - assets/logos/Elite.png
   - assets/logos/Gold.png
   - assets/logos/Platinum.png
   - assets/logos/Roar.png
   - assets/logos/Royal.png
   - assets/logos/Silver.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf